# Generated by Django 4.1.2 on 2022-10-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
    ]
