# Generated by Django 4.1.2 on 2022-10-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_new_total_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='new',
            name='total_views',
        ),
        migrations.AddField(
            model_name='new',
            name='views',
            field=models.ManyToManyField(blank=True, default=0, related_name='post_views', to='news.ip'),
        ),
    ]
