# Generated by Django 4.1.2 on 2022-10-10 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_ip_remove_new_total_views_new_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ('-publish',), 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
