# Generated by Django 4.1.2 on 2022-10-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_new_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='post_views', to='news.ip'),
        ),
    ]
